import argparse
import os
import subprocess
import sys
from datetime import datetime

import requests


def run_command(command, check=True):
    """Runs a command, prints its output, and returns the stripped stdout."""
    print(f"Running command: {' '.join(command)}")
    try:
        result = subprocess.run(
            command, capture_output=True, text=True, check=check, encoding="utf-8"
        )
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {' '.join(command)}", file=sys.stderr)
        print(e.stdout, file=sys.stderr)
        print(e.stderr, file=sys.stderr)
        raise


def main():
    parser = argparse.ArgumentParser(description="Create a PR for dependency updates if needed.")
    parser.add_argument("--workspace", required=True, help="GitHub workspace path.")
    parser.add_argument("--deps-file-path", required=True, help="Relative path to the dependency file to check.")
    parser.add_argument("--base-branch", required=True, help="The base branch for the pull request.")
    args = parser.parse_args()

    os.chdir(args.workspace)

    # 1. Check for changes
    status_output = run_command(["git", "status", "--porcelain", args.deps_file_path])
    if not status_output:
        print(f"No changes detected in {args.deps_file_path}. No PR will be created.")
        return

    print(f"Changes detected in {args.deps_file_path}. Proceeding to create a PR.")

    # 2. Get required environment variables
    github_token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")
    if not github_token or not repo:
        print("Error: GITHUB_TOKEN and GITHUB_REPOSITORY environment variables must be set.", file=sys.stderr)
        sys.exit(1)

    # 3. Configure Git
    run_command(["git", "config", "user.name", "github-actions[bot]"])
    run_command(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"])

    # 4. Create and push a new branch
    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    branch_name = f"check-all-libraries-{timestamp}"

    run_command(["git", "checkout", "-b", branch_name])
    run_command(["git", "add", args.deps_file_path])
    run_command(["git", "commit", "-m", "chore: Update actual dependencies list"])
    run_command(["git", "push", "origin", branch_name])

    # 5. Create the Pull Request
    api_url = f"https://api.github.com/repos/{repo}/pulls"
    headers = {"Authorization": f"token {github_token}", "Accept": "application/vnd.github.v3+json"}
    data = {
        "title": "[Automated] Update Actual Dependencies List",
        "body": "This PR was auto-generated by the 'Dependencies Check For All Libraries' workflow.\nIt contains updates to the `ActualDepsList.adeps` file based on the latest dependency scan.",
        "head": branch_name,
        "base": args.base_branch,
    }

    print(f"Creating pull request to merge {branch_name} into {args.base_branch}...")
    print(f"API URL: {api_url}")
    response = requests.post(api_url, headers=headers, json=data)
    try:
        response.raise_for_status()
    except requests.exceptions.HTTPError as e:
        print(f"API Error: {e}", file=sys.stderr)
        # The response body often contains a more detailed error message from GitHub.
        print(f"Response Body: {response.text}", file=sys.stderr)
        sys.exit(1)

    print("Successfully created pull request:", response.json()["html_url"])

if __name__ == "__main__":
    # For local testing:
    # 1. Manually change the deps file (e.g., Source/ActualDependencies/ActualDepsList.adeps)
    # 2. Set environment variables: GITHUB_TOKEN and GITHUB_REPOSITORY (e.g., "owner/repo")
    # 3. Run the script from the repository root: `uv run python scripts/src/scripts/create_pr_for_deps.py`
    if len(sys.argv) == 1:
        print("--- Running in local test mode with default arguments ---")

        # Set environment variables for local testing if they are not already set in the shell
        os.environ.setdefault("GITHUB_TOKEN", "")
        os.environ.setdefault("GITHUB_REPOSITORY", "karthickshanmugarao/sw-deps-monitor")
        os.environ.setdefault("GITHUB_TOKEN", "your_github_pat_here")
        os.environ.setdefault("GITHUB_REPOSITORY", "your_owner/your_repo")

        # Add a check to ensure placeholder values are replaced before proceeding
        if os.getenv("GITHUB_TOKEN") == "your_github_pat_here" or os.getenv("GITHUB_REPOSITORY") == "your_owner/your_repo":
            print("Error: For local testing, please replace placeholder values for GITHUB_TOKEN and GITHUB_REPOSITORY in create_pr_for_deps.py or set them as environment variables.", file=sys.stderr)
            sys.exit(1)

        sys.argv.extend([
            "--workspace", ".",
            "--deps-file-path", "Source/ActualDependencies/ActualDepsList.adeps",
            "--base-branch", "main"
        ])
    main()
